
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-3
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOB8qE7g","is_bot":false,"login":"tmcanepa","name":"Tyler Canepa"},"headRefName":"TylerC-edit","number":89,"title":"Edit Page for RecommendationRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-3/pull/89"},{"author":{"id":"U_kgDOBXy3rA","is_bot":false,"login":"andrew-kwon1","name":""},"headRefName":"ak-helprequest-tablecomponent","number":79,"title":"HelpRequest Table Component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-3/pull/79"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-Test","number":78,"title":"[h05] [do NOT merge] Integration / E2E tests for h05","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-3/pull/78"}]
